### PR TITLE
Authentication endpoints

### PR DESCRIPTION
**Pull request by blueteamcpu**

### CODE REVIEW

**Review by nicknapoli82 — COMMENTED** [review]
I think we need to explore what data we send back to the client just a bit. It appears we are sending all user data back from the server, including the hashed password and so forth.

We may want to be selective in what we send.

**Comment by justin-cook-developer** [comment]
@nicknapoli82 we are sending back everything but password. The toJSON method will remove a password before sending. Here is an example:
`    "id": "06124cc0-0b89-489c-bdbf-92fe53c64692",
    "imageURL": "https://upload.wikimedia.org/wikipedia/commons/6/67/User_Avatar.png",
    "isSiteAdmin": false,
    "firstName": "Justin",
    "lastName": "Cook",
    "username": "jman",
    "zipcode": 93420,
    "email": "justin@email.com",
    "updatedAt": "2019-09-06T16:37:53.561Z",
    "createdAt": "2019-09-06T16:37:53.561Z"
}`

**Comment by justin-cook-developer** [comment]
Do you think we should remove zipcode?

**Comment by nicknapoli82** [comment]
I didn't realize the toJSON method removes the password implicitly. I think the zip code is actually something needed on the client side... Should we want to filter or sort data on the client side pulling most relevant events, for example, to the top of a list.

Maybe we just have the server do that also though.

I don't see the other information being to bad to send to the client.

**Review by nicknapoli82 — APPROVED** [review]

**Pull request merged**
